<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>WorldServer</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" />
    <PackageReference Include="Microsoft.VisualBasic" />
    <PackageReference Include="System.CodeDom" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mangos.Common.Legacy\Mangos.Common.Legacy.csproj" />
    <ProjectReference Include="..\Mangos.Configuration\Mangos.Configuration.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Objects\Factories\Creatures\" />
  </ItemGroup>

</Project>